### ISSUE TITLE
how to visit frontend page

### ISSUE THREAD

**Issue by dachengcheng2022** [ethpandaops/dora#152]
how to config 'ethExplorerLink'

**Comment by dachengcheng2022** [comment]
![image](https://github.com/user-attachments/assets/26e17fcc-f841-4d0d-a59b-680edf0c461a)
when i visite http://ip:8080, not anyting response

**Comment by avenbreaks** [comment]
> ![image](https://private-user-images.githubusercontent.com/21340057/376302007-26e17fcc-f841-4d0d-a59b-680edf0c461a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjY3MjksIm5iZiI6MTcyODkyNjQyOSwicGF0aCI6Ii8yMTM0MDA1Ny8zNzYzMDIwMDctMjZlMTdmY2MtZjg0MS00ZDBkLWE1OWItNjgwZWRmMGM0NjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE3MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhN2EwYTRiYzk2M2NiOTgwMzRkMzFlOWVmZjMzNDE2NTU1MTliNjFmNThkMjk4NjllZWZkOGEzMzQ0ZTM2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SdHzMcqK3H4TO_KCohULZ1thBM0GeYysjhhBXL660ho) when i visite http://ip:8080, not anyting response

try change with your public ip or domain, 

`tcp   LISTEN 0      4096         0.0.0.0:9898       0.0.0.0:*    users:(("docker-proxy",pid=31812,fd=4)) `

**Comment by pk910** [comment]
> how to config 'ethExplorerLink'

This is the base url to an execution explorer if present.
You can configure it like this:
```
ethExplorerLink: "https://sepolia.etherscan.io/"  # replace with the base url of your block explorer
```
or just leave it blank if you don't have a block explorer running.


> when i visite http://ip:8080/, not anyting response

I'm not sure what's the reason for this.  Can you share more details about your setup? 
How do you run dora?  ad docker image / executable?
What does no response mean?  Does it load forever or does it show a http error?

**Comment by dachengcheng2022** [comment]
i build from source code
./dora-explorer -config ./explorer-config.yaml
`
logging:
  outputLevel: "debug"
  outputStderr: false

  filePath: "explorer.log"
  fileLevel: "debug"

# Chain network configuration
chain:
  displayName: "OR BEACON EXPLORER"

# HTTP Server configuration
server:
  host: "0.0.0.0" # Address to listen on
  port: "8080" # Port to listen on

frontend:
  enabled: true # Enable or disable to web frontend
  debug: true
  minimize: false # minimize html templates

  # Name of the site, displayed in the title tag
  siteName: "OR BEACON EXPLORER"
  siteSubtitle: ""
  siteDomain: "beacon.orex.work"
  # link to EL Explorer
  ethExplorerLink: "http://beacon.orex.work/"

  # file or inventory url to load validator names from
  validatorNamesYaml: ""
  validatorNamesInventory: ""
  
beaconapi:
  # beacon node rpc endpoints
  endpoints:
    - name: "orchain"
      url: "http://52.76.172.102:3500"

  # local cache for page models
  localCacheSize: 100 # 100MB

  # remote cache for page models
  redisCacheAddr: ""
  redisCachePrefix: ""

executionapi:
  # execution node rpc endpoints
  endpoints:
    - name: "orchain"
      url: "http://52.76.172.102:8545"
  
  depositLogBatchSize: 1000

# indexer keeps track of the latest epochs in memory.
indexer:
  # max number of epochs to keep in memory
  inMemoryEpochs: 3

  # disable synchronizing historic data
  disableSynchronizer: false

  # reset synchronization state to this epoch on startup - only use to resync database, comment out afterwards
  #resyncFromEpoch: 0

  # force re-synchronization of epochs that are already present in DB - only use to fix missing data after schema upgrades
  #resyncForceUpdate: true

  # number of seconds to pause the synchronization between each epoch (don't overload CL client)
  syncEpochCooldown: 2

  # maximum number of parallel beacon state requests (might cause high memory usage)
  maxParallelValidatorSetRequests: 1

# database configuration
database:
  engine: "sqlite" # sqlite / pgsql

  # sqlite settings (only used if engine is sqlite)
  sqlite:
    file: "./explorer-db.sqlite"

  # pgsql settings (only used if engine is pgsql)
  pgsql:
    host: "127.0.0.1"
    port: 5432
    user: ""
    password: ""
    name: ""
  pgsqlWriter: # optional separate writer connection (used for replication setups)
    host: ""
    port: 5432
    user: ""
    password: ""
    name: ""
`

**Comment by dachengcheng2022** [comment]
> 9898

do you mean need run an additional block explorer ?
do you know open source block explorer repository ?

**Comment by dachengcheng2022** [comment]
![image](https://github.com/user-attachments/assets/6cb147a0-cd96-4eef-b39e-452f31b0a48e)
when i visite this ,not anything response

**Comment by pk910** [comment]
ok,  thanks for the details :)

Yea, the reason for that big error message is that you've enabled the debug mode.
This debug mode is designed to load the page templates from source code, instead of loading them from the binary. That's very helpful to speed up development, but doesn't work when running the compiled binary without the source code around.

So, switch this:
```
frontend:
  debug: false
```

rest of the config looks fine and should work :)

**Comment by skylenet** [comment]
> > i build from source code ./dora-explorer -config ./explorer-config.yaml
> > The screenshot is my configuration file
> > ![image](https://private-user-images.githubusercontent.com/21340057/376431196-5a52cdcd-3782-4ccd-92d8-222349d0e920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDMwNzEsIm5iZiI6MTcyOTAwMjc3MSwicGF0aCI6Ii8yMTM0MDA1Ny8zNzY0MzExOTYtNWE1MmNkY2QtMzc4Mi00Y2NkLTkyZDgtMjIyMzQ5ZDBlOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4N2ZkMDMzMDdjZGRkMjQ2YmM2NGI2ZTgxY2VhNTlmNTdjNzg3NTk0ZjkwYTc3N2Q4Yjk1OGMwZjI2MzQ0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fMVsyjJ8yjZPfXTbsb1KsBJG4qAjCO6kpVj0navMj_o) ![image](https://private-user-images.githubusercontent.com/21340057/376431265-071bd287-739f-4acf-9c08-d387e8f81a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDMwNzEsIm5iZiI6MTcyOTAwMjc3MSwicGF0aCI6Ii8yMTM0MDA1Ny8zNzY0MzEyNjUtMDcxYmQyODctNzM5Zi00YWNmLTljMDgtZDM4N2U4ZjgxYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4N2Y5NzIwNGFjOGRhYTRhODZhY2IyNGYzOTllNjkxMjhiYTI2NTkyZWI1YWU3YTRiYjY1MGEzMWZlMmNhZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FBohReG4ZYbD3Dm-4cUzOJKfF3r1Cdf3TGBUBG0G6lA)
> > i run it ,but i dont know how to visite frontend page ![image](https://private-user-images.githubusercontent.com/21340057/376450234-960e32e6-9154-4752-b8a3-44f54e1749d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDMwNzEsIm5iZiI6MTcyOTAwMjc3MSwicGF0aCI6Ii8yMTM0MDA1Ny8zNzY0NTAyMzQtOTYwZTMyZTYtOTE1NC00NzUyLWI4YTMtNDRmNTRlMTc0OWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMmI0NDY5ZmI1MmZhMDU2NjYzZmUyN2M1NTk0YmFmYzBiZTkzNjlmNTg5MzU1MGFiNWFjYjJmNzFmMjJiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZnOJf8lxyhAQQeo8kqSF0gyA3KudNw8L6BcfTXfy2UY)
> 
> hijacking this just to ask a quick question
> 
> are you connecting Dora to your private testnet?
> 
> i would appreciate some advice on how you did that

I replied to you here: https://github.com/ethpandaops/dora/issues/153#issuecomment-2414115801

**Comment by dachengcheng2022** [comment]
thanks, it work well now
