### ISSUE TITLE
why cant find validator info

### ISSUE THREAD

**Issue by dachengcheng2022** [ethpandaops/dora#155]
`curl --location 'http://52.76.172.102:3500/eth/v1/beacon/states/head/validators'`  this is beancon api , has one validtor
![image](https://github.com/user-attachments/assets/6446c816-44be-4b8d-a018-93fad19df1d2)

but, website has not validtor info

http://47.237.4.148:8080/validators

i build from source code, used pgsql

**Comment by pk910** [comment]
yea, something seems to be wrong with your instance :/
It looks like a bug. can you provide us the dora logs? 
There must be some error messages

**Comment by dachengcheng2022** [comment]
![image](https://github.com/user-attachments/assets/ac9a630e-5114-4c3f-aaf1-1d7e87ed2b88)
how can i send you log ? do you have chat software,like tg,discord ?
