### ISSUE TITLE
Thank you for this great project

### ISSUE THREAD

**Issue by canximan** [ethpandaops/dora#53]
Dear @ethpandaops 

We used Dora for our project: Canxium, it's really awesome, could you please give us your wallet, we'd like to send you some CAU coin as a donation (metamask wallet is fine)

Best Regards.
Neo Krypt.

**Comment by pk910** [comment]
Heya @canximan.
Thanks for your feedback :) 
It's great to hear that dora is valuable for other projects as well :)

For a donation, you can use `pk910.eth`, I'll gonna share it with the rest of the team.

If you're planning a bigger token drop at some time,  consider a allocation for the protocol guild (https://protocol-guild.readthedocs.io/en/latest/).
That way you're appreciating all the core devs that work on ethereum clients & core infrastructure.

Best Regards,
pk910

**Comment by canximan** [comment]
Hi @pk910 

I have donated 45 CAU to `pk910.eth`, thank you very much and hope you and your team keep going to build this great project.

https://scan.canxium.org/tx/0xef5cd2547e60195f920c36f32c5273e88cf1e9a441f4f1a445944f4e19dfff2c

Best Rewards.
Neo Krypt.
