### ISSUE TITLE
Minimal preset doesn't work

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/dora#54]
if config.yaml has minimal preset, dora becomes unhappy.

![Screenshot 2024-03-25 at 17 30 10](https://github.com/ethpandaops/dora/assets/21987084/65b718bd-42ab-4381-901b-7c6eb2d499ad)

All nodes are still connected, but they all report that they stuck syncing at slot 1. 

None of the slots seem to be proposed, even tho they were. 

To repro:

`kurtosis run github.com/kurtosis-tech/ethereum-package@bbusa/preset --args-file https://github.com/kurtosis-tech/ethereum-package/blob/bbusa/preset/.github/tests/minimal.yaml`

**Comment by pk910** [comment]
#55 adds support for the minimal preset :)
